### ISSUE TITLE
./trigmap.sh: line 212: syntax error near unexpected token `fi' ./trigmap.sh: line 212: `fi'

### ISSUE THREAD

**Issue by jordantsap** [Leviathan36/trigmap#1]
Running ./trigmap.sh in the trigmap folder it shows that error.
Why is that in: 
./trigmap.sh: line 212: syntax error near unexpected token `fi'
./trigmap.sh: line 212: `fi'

**Comment by hackzaid** [comment]
Solution:
vim +212 trigmap.sh

Delete "fi" on that line, save and run script again

**Comment by jordantsap** [comment]
Maybe +1 closing if statement right???

**Comment by hackzaid** [comment]
> 
> 
> Maybe +1 closing if statement right???

Sure.... :)

**Comment by jordantsap** [comment]
Yes thats fixed when commenting the line 212 which is the +1 ending if
